jobs:
  create_release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-jdk-17-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-jdk-17-maven-
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_USER: ${{ secrets.GH_USER }}
      name: Create Release
      run: 'build-bin/git/login_git &&

        build-bin/maven/maven_release $(echo ${GITHUB_REF} | cut -d/ -f 3)

        '
name: create_release
on:
  repository_dispatch:
    types: trigger-ga___create_release.yml
