jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-jdk-17-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-jdk-17-maven-
    - continue-on-error: true
      name: Cache NPM Packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-npm-packages-${{ hashFiles('zipkin-lens/package-lock.json')
          }}
        path: ~/.npm
    - continue-on-error: true
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_USER: ${{ secrets.GH_USER }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      name: Deploy
      run: 'build-bin/configure_deploy &&

        build-bin/deploy $(echo ${GITHUB_REF} | cut -d/ -f 3)

        '
name: deploy
on:
  repository_dispatch:
    types: trigger-ga___deploy.yml
