jobs:
  lint:
    if: '!contains(github.event.head_commit.message, ''maven-release-plugin'')'
    name: lint
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Lint
      run: 'build-bin/configure_lint

        build-bin/lint

        '
name: lint
on:
  repository_dispatch:
    types: trigger-ga___lint.yml
