jobs:
  security:
    if: '!contains(github.event.head_commit.message, ''maven-release-plugin'')'
    name: security
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache Trivy Database
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-trivy
        path: .trivy
        restore-keys: ${{ runner.os }}-trivy
    - continue-on-error: true
      id: trivy
      name: Run Trivy vulnerability and secret scanner
      uses: aquasecurity/trivy-action@master
      with:
        cache-dir: .trivy
        exit-code: '1'
        output: trivy-report.md
        scan-ref: .
        scan-type: fs
        scanners: vuln,secret
        severity: HIGH,CRITICAL
    - continue-on-error: true
      if: ${{ failure() && steps.trivy.conclusion == 'failure' }}
      name: Set Summary
      run: cat trivy-report.md >> $GITHUB_STEP_SUMMARY
      shell: bash
name: security
on:
  repository_dispatch:
    types: trigger-ga___security.yml
