jobs:
  docker:
    if: '!contains(github.event.head_commit.message, ''maven-release-plugin'')'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Remove broken apt repos
      run: 'for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`

        do sudo rm $apt_file

        done

        '
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      name: Cache NPM Packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-npm-packages-${{ hashFiles('zipkin-lens/package-lock.json')
          }}
        path: ~/.npm
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -T1C -q --batch-mode -DskipTests
      name: Build zipkin-server
      run: ./mvnw --also-make -pl zipkin-server clean package
    - continue-on-error: true
      env:
        RELEASE_FROM_MAVEN_BUILD: true
      name: docker/README.md - openzipkin/zipkin
      run: "build-bin/docker/docker_build openzipkin/zipkin:test &&\nbuild-bin/docker/docker_test_image\
        \ openzipkin/zipkin:test &&\ndocker run --rm --entrypoint=/bin/sh openzipkin/zipkin:test\
        \ \\\n  -c 'cd BOOT-INF/lib && du -sk *aarch* *x86* *a64*' || true\n"
    - continue-on-error: true
      env:
        DOCKER_TARGET: zipkin-slim
        RELEASE_FROM_MAVEN_BUILD: true
      name: docker/README.md - openzipkin/zipkin-slim
      run: "build-bin/docker/docker_build openzipkin/zipkin-slim:test &&\nbuild-bin/docker/docker_test_image\
        \ openzipkin/zipkin-slim:test &&\ndocker run --rm --entrypoint=/bin/sh openzipkin/zipkin-slim:test\
        \ \\\n  -c 'cd BOOT-INF/lib && du -sk *aarch* *x86* *a64*' || true\n"
    - continue-on-error: true
      env:
        DOCKER_FILE: docker/test-images/zipkin-ui/Dockerfile
        DOCKER_TAG: openzipkin/zipkin-ui:test
        RELEASE_FROM_MAVEN_BUILD: true
      name: docker/test-images/zipkin-ui/README.md
      run: 'build-bin/docker/docker_build ${DOCKER_TAG} &&

        build-bin/docker/docker_test_image ${DOCKER_TAG}

        '
    - continue-on-error: true
      env:
        DOCKER_FILE: docker/test-images/zipkin-uiproxy/Dockerfile
        DOCKER_TAG: openzipkin/zipkin-uiproxy:test
      name: docker/test-images/zipkin-uiproxy/README.md
      run: 'build-bin/docker/docker_build ${DOCKER_TAG} &&

        build-bin/docker/docker_test_image ${DOCKER_TAG}

        '
    - continue-on-error: true
      env:
        DOCKER_FILE: docker/test-images/zipkin-activemq/Dockerfile
        DOCKER_TAG: openzipkin/zipkin-activemq:test
      name: docker/test-images/zipkin-activemq/README.md
      run: 'build-bin/docker/docker_build ${DOCKER_TAG} &&

        build-bin/docker/docker_test_image ${DOCKER_TAG}

        '
    - continue-on-error: true
      env:
        DOCKER_FILE: docker/test-images/zipkin-cassandra/Dockerfile
        DOCKER_TAG: openzipkin/zipkin-cassandra:test
      name: docker/test-images/zipkin-cassandra/README.md
      run: 'build-bin/docker/docker_build ${DOCKER_TAG} &&

        build-bin/docker/docker_test_image ${DOCKER_TAG}

        '
    - continue-on-error: true
      env:
        DOCKER_FILE: docker/test-images/zipkin-elasticsearch7/Dockerfile
        DOCKER_TAG: openzipkin/zipkin-elasticsearch7:test
      name: docker/test-images/zipkin-elasticsearch7/README.md
      run: 'build-bin/docker/docker_build ${DOCKER_TAG} &&

        build-bin/docker/docker_test_image ${DOCKER_TAG}

        '
    - continue-on-error: true
      env:
        DOCKER_FILE: docker/test-images/zipkin-elasticsearch8/Dockerfile
        DOCKER_TAG: openzipkin/zipkin-elasticsearch8:test
      name: docker/test-images/zipkin-elasticsearch8/README.md
      run: 'build-bin/docker/docker_build ${DOCKER_TAG} &&

        build-bin/docker/docker_test_image ${DOCKER_TAG}

        '
    - continue-on-error: true
      env:
        DOCKER_FILE: docker/test-images/zipkin-opensearch2/Dockerfile
        DOCKER_TAG: openzipkin/zipkin-opensearch2:test
      name: docker/test-images/zipkin-opensearch2/README.md
      run: 'build-bin/docker/docker_build ${DOCKER_TAG} &&

        build-bin/docker/docker_test_image ${DOCKER_TAG}

        '
    - continue-on-error: true
      env:
        DOCKER_FILE: docker/test-images/zipkin-eureka/Dockerfile
      name: docker/test-images/zipkin-eureka/README.md
      run: 'build-bin/docker/docker_build openzipkin/zipkin-eureka:test &&

        build-bin/docker/docker_test_image openzipkin/zipkin-eureka:test

        '
    - continue-on-error: true
      env:
        DOCKER_FILE: docker/test-images/zipkin-kafka/Dockerfile
      name: docker/test-images/zipkin-kafka/README.md
      run: 'build-bin/docker/docker_build openzipkin/zipkin-kafka:test &&

        build-bin/docker/docker_test_image openzipkin/zipkin-kafka:test

        '
    - continue-on-error: true
      env:
        DOCKER_FILE: docker/test-images/zipkin-mysql/Dockerfile
      name: docker/test-images/zipkin-mysql/README.md
      run: 'build-bin/docker/docker_build openzipkin/zipkin-mysql:test &&

        build-bin/docker/docker_test_image openzipkin/zipkin-mysql:test

        '
    - continue-on-error: true
      env:
        DOCKER_FILE: docker/test-images/zipkin-rabbitmq/Dockerfile
      name: docker/test-images/zipkin-rabbitmq/README.md
      run: 'build-bin/docker/docker_build openzipkin/zipkin-rabbitmq:test &&

        build-bin/docker/docker_test_image openzipkin/zipkin-rabbitmq:test

        '
    timeout-minutes: 10
  zipkin-server:
    if: '!contains(github.event.head_commit.message, ''maven-release-plugin'')'
    name: zipkin-server/README.md ${{ matrix.name }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      name: Cache NPM Packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-npm-packages-${{ hashFiles('zipkin-lens/package-lock.json')
          }}
        path: ~/.npm
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -T1C -q --batch-mode -DskipTests
      name: Execute Server Build
      run: ./mvnw --also-make -pl zipkin-server clean package
    strategy:
      matrix:
        include:
        - name: macos
          os: macos-13
        - name: windows
          os: windows-2022
    timeout-minutes: 5
name: test_readme
on:
  repository_dispatch:
    types: trigger-ga___test_readme.yml
