jobs:
  test:
    if: '!contains(github.event.head_commit.message, ''maven-release-plugin'')'
    name: test (JDK ${{ matrix.java_version }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.java_version }}
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-jdk-${{ matrix.java_version }}-maven-${{ hashFiles('**/pom.xml')
          }}
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-jdk-${{ matrix.java_version }}-maven-
    - continue-on-error: true
      name: Cache NPM Packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-npm-packages-${{ hashFiles('zipkin-lens/package-lock.json')
          }}
        path: ~/.npm
    - continue-on-error: true
      name: Test without Docker
      run: 'build-bin/maven_go_offline &&

        build-bin/test -DexcludedGroups=docker ${{ matrix.maven_args }}

        '
    strategy:
      fail-fast: false
      matrix:
        include:
        - java_version: 17
          maven_args: -Prelease -Dgpg.skip
        - java_version: 21
  test_docker:
    if: '!contains(github.event.head_commit.message, ''maven-release-plugin'')'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-jdk-${{ matrix.java_version }}-maven-${{ hashFiles('**/pom.xml')
          }}
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-jdk-${{ matrix.java_version }}-maven-
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -Dlicense.skip=true
        MAVEN_GOAL: install
      name: Test with Docker
      run: 'build-bin/docker/configure_docker &&

        build-bin/maven/maven_go_offline &&

        build-bin/maven/maven_build -pl :${{ matrix.name }} --am &&

        build-bin/test -Dgroups=docker -pl :${{ matrix.name }}

        '
    strategy:
      matrix:
        include:
        - name: zipkin-collector-activemq
        - name: zipkin-collector-kafka
        - name: zipkin-collector-rabbitmq
        - name: zipkin-storage-cassandra
        - name: zipkin-storage-elasticsearch
        - name: zipkin-storage-mysql-v1
        - name: zipkin-server
name: test
on:
  repository_dispatch:
    types: trigger-ga___test.yml
